# Generated by Django 5.2.9 on 2026-03-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('poster', models.URLField()),
                ('url', models.URLField()),
                ('source', models.CharField(choices=[('yummyanime.tv', 'Yummyanimetv')], max_length=50)),
            ],
        ),
    ]
