# Generated by Django 5.2.9 on 2026-03-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
