# Generated by Django 5.2.9 on 2026-03-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='external_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
