# Generated by Django 5.2.9 on 2026-03-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_sourcesession_alter_movie_options_movie_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('series', 'Series'), ('movie', 'Movie')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
