# Generated by Django 5.2.9 on 2026-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fill_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='fill_poster',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='fill_title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
