# Generated by Django 5.2.9 on 2026-03-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_fill_description_movie_fill_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='fill_poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
