# Generated by Django 5.2.9 on 2026-03-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_fill_poster_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', unique=True),
        ),
    ]
