# Generated by Django 5.2.9 on 2026-03-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_history_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
