# Generated by Django 5.2.9 on 2026-03-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_translation_movieepisode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('headers', models.JSONField(default=dict)),
                ('deta', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
