# Generated by Django 5.2.9 on 2026-03-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_socket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socket',
            old_name='deta',
            new_name='data',
        ),
        migrations.AddField(
            model_name='socket',
            name='episode_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
