# Generated by Django 5.2.12 on 2026-03-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_browsersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='source',
            field=models.CharField(choices=[('yummyanime.tv', 'Yummyanimetv'), ('uakinogo.ec', 'Uakinogoec')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sourcesession',
            name='source',
            field=models.CharField(choices=[('yummyanime.tv', 'Yummyanimetv'), ('uakinogo.ec', 'Uakinogoec')], max_length=50),
        ),
    ]
